import telebot
import time
import requests
from PIL import Image

bot_token = ''    # Enter your bot's token here.
bot = telebot.TeleBot(token=bot_token)


def scrape():

    url = "https://thispersondoesnotexist.com/image"
    r = requests.get(url)
    if r.status_code == 200:
        with open("sample.jpg", 'wb') as f:
            f.write(r.content)
        return "sample.jpg"
    else:
        return 0


@bot.message_handler(commands=['start'])
def send_welcome(message):

    bot.reply_to(message, f"Welcome, {message.from_user.first_name}! Send /help if you are new here.")


@bot.message_handler(commands=['help'])
def send_welcome(message):

    bot.reply_to(message, '*Everytime you send a message (except GIFs and stickers) to us, you will '
                 + 'receive a fake face generated by AI, directly scraped from ThisPersonDoesNotExist.com.*', parse_mode='Markdown')


@bot.message_handler(func=lambda message: True)
def at_answer(message):

    photo_name = scrape()
    if photo_name:
        bot.reply_to(message, "_Downloading file..._", parse_mode='Markdown')
        photo = Image.open(photo_name)
        bot.send_photo(message.chat.id, photo)
    else:
        bot.reply_to(message, "*Something went wrong. Please try again.*", parse_mode='Markdown')


while True:
    try:
        bot.polling()
    except Exception:
        time.sleep(15)